### PR TITLE
Improves docu for auth_kbdint_getprompt and example

### PR DESCRIPTION
**Pull request by brodafly**
Hi,

I forgot to return the user credentials back to the ones used for the other examples. Probably in the future they can be refactored to accept cmd line values and/or interactively collect the user input.

Also improved the documentation for the auth_kbdint_getprompt to show what the returned hash contains.

### CODE REVIEW

**Comment by brodafly** [comment]
Should've put the hash table return info below the info about the OPTIONS hash... will amend

**Comment by garnier-quentin** [comment]
Thank you. In which case do you use libssh perl ?

**Comment by brodafly** [comment]
No problem! Thanks for the reviews. I need to migrate a piece of code currently using libssh2 + Net::SSH2 to libssh. It was a huge help to find this repo. Since some functionality used from the Net::SSH2 is still not available here I'm trying to add it. There's one thing left to add and that's to enable non-blocking executions of commands to remote SSH servers. I thought that would be the most dreadful of all so I left it for last. 😄

**Comment by garnier-quentin** [comment]
You can already enable non-blocking executions of commands to remote SSH servers.  It's not what the script 'client_execute_parallel.pl' does ?

**Comment by brodafly** [comment]
From my understanding in 'client_execute_parallel.pl' you're starting several commands in parallel on one server. My target use case is slightly different. I want to start one (or several, for that matter) commands but on several servers in a non-blocking matter.

In the Net::SSH2 code I'm trying to migrate this is implemented by directly using the channel objects. From an SSH session you get the associated channel object and you set it to non-blocking. Then 'exec' is called with the command you want to execute. Then you periodically read the output of the channel object until you get an end-of-file from the server. That's how you know the command terminated. And you can do this for several channel's belonging to different SSH sessions. That's what I meant by non-blocking execution which was probably a wrong term to use on my side, sorry. 😁

I'm not sure if something similar can be done with perl-libssh at the moment, but I'm about to start investigating.

**Comment by garnier-quentin** [comment]
Excalty. It's on the same server yes. I didn't do on multiple ssh servers.
It can be done i think also. 

But why do you want to use libssh perl if you have everything with libssh2 perl ?

**Comment by brodafly** [comment]
Because it turns out that on RHEL8.x libssh2 will not be delivered anymore due to security issues and they'll start shipping with libssh. So that's why I'm adapting the current functionality to work with libssh.

**Comment by brodafly** [comment]
Yeah, hopefully. It's good that this repo exists. AFAIK SLES are also considering libssh2 a legacy package. So the future looks bright for libssh 😄

**Pull request merged**
