### PR TITLE
Add handling for possible race condition when exiting channel

### PR DESCRIPTION
**Pull request by vesislavdimitrov**
So I have recently discovered an issue where under certain circumstances  there is a possibility that the C implementation of libssh might stub on a race condition where the EOF exit code (-1) is returned before the real exit status of the channel which leads to a failure in my personal use case. The issue is very hard to reproduce but I managed to find this old thread where somebody explained how they have handled it: https://libssh.libssh.narkive.com/fQcBJm2p/get-exit-code-of-a-executed-remote-command

Basically, they added this loop to filter out the wrong exit codes before closing the channel. The numbers I have used here are completely in line with what was offered as tested in this thread and I haven't experimented with altering the values. I added this fix locally and tested it heavily over the course of the last week and the issue seems to be resolved.

Since it really does seem weird to just randomly loop over these exit codes for X amount of time I am open to suggestions on how to elegantly handle this.

Cheers.

### CODE REVIEW

**Comment by vesislavdimitrov** [comment]
Hi @garnier-quentin ,
Have you had the time to take a look at this?

**Comment by garnier-quentin** [comment]
Thanks for the detailed PR. I think it's an issue with some buggy ssh daemon. For me the workaround it's ok. 

What exactly happen when you have the problem ? There is a memory/fd leak, a function is stuck ?

**Comment by vesislavdimitrov** [comment]
Well, the return code of the channel exit is -1 which is handled as a failure.

**Comment by garnier-quentin** [comment]
Ok i see. I don't see how we can handle it. For me the PR is fine. I will do a release tomorrow.

Thanks!

**Review by garnier-quentin — APPROVED** [review]

**Comment by garnier-quentin** [comment]
Sorry for the delay. the release is pushed on metacpan.

**Comment by vesislavdimitrov** [comment]
Hi @garnier-quentin,

Sorry for bothering you again but I am afraid I don't see the new version @ https://metacpan.org/pod/Libssh::Session

Is everything ok?

**Comment by garnier-quentin** [comment]
https://metacpan.org/release/QGARNIER/Libssh-Session-1.0/view/lib/Libssh/Session.pm

It seems ok for me

**Comment by vesislavdimitrov** [comment]
Interesting, I don't know why but the metacpan search was pointing to the 0.8 release. Sorry and thank you.

**Comment by vesislavdimitrov** [comment]
I just noticed that 1.0 is not marked as latest at metacpan. This is the metadata I get from the fastapi:

{
   "status" : "latest",
   "version" : "0.8",
   "download_url" : "https://cpan.metacpan.org/authors/id/Q/QG/QGARNIER/Libssh-Session-0.8.tar.gz"
}

**Comment by garnier-quentin** [comment]
I'm waiting the deletion of the version 1.0 (dont know when it should be ok. it's scheduled by "pause" but we don't know when). After that, i will reupload it with ```META.json``` file.

**Comment by garnier-quentin** [comment]
@vesislavdimitrov it should be ok!

**Pull request merged**
